import React from "react";
import Navbar from "../../components/Navbar";
import styles from "../../styles/Siteminder.module.css";
import "antd/dist/antd.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Head } from "next/head";
import { Row, Col } from "react-bootstrap";
import { DatePicker } from "antd";
import { GrRotateLeft } from "react-icons/gr";
import { FaBed } from "react-icons/fa";
import {
  AiOutlineDoubleRight,
  AiOutlineDoubleLeft,
  AiFillThunderbolt,
  AiFillEdit,
} from "react-icons/ai";
import { MdOutlineArrowDropDown, MdRefresh } from "react-icons/md";
import { BsFillTagFill } from "react-icons/bs";
import { IoIosSave, IoMdArrowDropdown } from "react-icons/io";
import { GiCancel } from "react-icons/gi";

const ChannelManager = () => {
  const router = useRouter();
  const { propertyId } = router.query;
  const [roomDropdown, setRoomDropdown] = useState(false);
  const [planDropdown, setPlanDropdown] = useState(false);
  const [otaDropdown, setOtaDropdown] = useState(false);
  //   console.log(propertyId);

  //   const token = localStorage.getItem("token");
  //   console.log(token);

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (localStorage.getItem("token") && propertyId !== undefined) {
    }
    // console.log(token);
  }, [router]);
  return (
    <>
      <Navbar />
      <div className={styles.container}>
        <div className="flex justify-between">
          <div className="flex items-center">
            <h6 className="text-semibold mx-2">Travel Agency Name:</h6>
            <button
              onClick={() => setOtaDropdown(!otaDropdown)}
              className="bg-blue-900 text-xl font-semibold py-2 px-4 w-56 rounded flex items-center justify-between text-white border-none relative"
            >
              <div>Agoda</div>
              <div>
                <IoMdArrowDropdown size={28} />
              </div>
              {otaDropdown === true && (
                <div className="absolute bg-white w-full left-0 top-12 p-1 text-black text-md z-10 rounded text-sm">
                  <div className="p-1 rounded hover:bg-blue-600 hover:text-white">
                    YES
                  </div>
                </div>
              )}
            </button>
          </div>
          <div className="flex">
            <button className="bg-blue-900 flex items-center text-white justify-between px-3 w-full rounded mx-1">
              <div>
                <AiFillEdit size={26} />
              </div>
              <div className="text-lg font-semibold p-1 w-48">
                Update Inventory
              </div>
            </button>
            <button className="bg-blue-900 flex items-center text-white justify-between px-3 w-full rounded mx-1">
              <div>
                <AiFillEdit size={26} />
              </div>
              <div className="text-lg font-semibold p-1 w-48">
                Add or Update Plan
              </div>
            </button>
            <button className="bg-blue-900 flex items-center text-white justify-between px-3 w-full rounded mx-1">
              <div>
                <MdRefresh size={26} />
              </div>
              <div className="text-lg font-semibold p-1">Clear</div>
            </button>
          </div>
        </div>
        {/* <Head>
          <title>MMT Channel Manager</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> */}
        <div className={styles.buttonGroup}>
          <Row>
            {/* <Col className={styles.buttons}> */}
            {/* <div
                style={{
                  width: "40%",
                  display: "flex",
                  justifyContent: "space-between",
                }}
              >

              </div> */}
            {/* </Col> */}
          </Row>
        </div>

        <div className={styles.table}>
          <div className={styles.topBar}>
            <Row className={styles.dateSection}>
              <Col className={styles.dateSelector}>
                <Col className="mt-2 gap-1 -ml-5">
                  <div style={{ display: "flex", justifyContent: "center" }}>
                    {/* <span>From: </span> */}
                    <DatePicker
                      size="small"
                      placeholder="From Date"
                      className="h-8 w-36"
                    />
                  </div>
                  <div style={{ display: "flex", justifyContent: "center" }}>
                    {/* <span>To: </span> */}
                    <DatePicker
                      placeholder="To Date"
                      size="small"
                      className="h-8 w-36"
                    />
                  </div>
                  <button className={`${styles.findRatesButton} px-3`}>
                    SEARCH
                  </button>
                </Col>
                <span className="py-1 -ml-10">
                  <GrRotateLeft
                    className="text-gray-200"
                    size={15}
                    style={{ marginRight: "10px" }}
                  />

                  <AiOutlineDoubleLeft
                    className="text-gray-200"
                    size={15}
                    style={{ marginRight: "10px" }}
                  />

                  <div className="text-gray-200">Date</div>

                  <AiOutlineDoubleRight
                    className="text-gray-200"
                    size={15}
                    style={{ marginLeft: "10px" }}
                  />
                </span>
              </Col>
              <Col className={styles.dates}>
                <Row className={styles.dateCards}>
                  <Col className={`${styles.dateCard} text-gray-200`}>
                    <span>Wed</span>
                    <span className={styles.boldDateText}>21</span>
                    <span>Sep</span>
                  </Col>
                  <Col className={`${styles.dateCard} text-gray-200`}>
                    <span>Thu</span>
                    <span className={styles.boldDateText}>22</span>
                    <span>Sep</span>
                  </Col>
                  <Col className={`${styles.dateCard} text-gray-200`}>
                    <span>Fri</span>
                    <span className={styles.boldDateText}>23</span>
                    <span>Sep</span>
                  </Col>
                  <Col className={`${styles.dateCard} text-gray-200`}>
                    <span>Sat</span>
                    <span className={styles.boldDateText}>24</span>
                    <span>Sep</span>
                  </Col>
                  <Col className={`${styles.dateCard} text-gray-200`}>
                    <span>Sun</span>
                    <span className={styles.boldDateText}>25</span>
                    <span>Sep</span>
                  </Col>
                  <Col className={`${styles.dateCard} text-gray-200`}>
                    <span>Mon</span>
                    <span className={styles.boldDateText}>26</span>
                    <span>Sep</span>
                  </Col>
                  <Col className={`${styles.dateCard} text-gray-200`}>
                    <span>Tue</span>
                    <span className={styles.boldDateText}>27</span>
                    <span>Sep</span>
                  </Col>
                </Row>
              </Col>
            </Row>
          </div>
          <Row className={`py-2`}>
            {/* <Col className={styles.Icon}></Col> */}
            <Col className={styles.leftSection} style={{ border: "none" }}>
              <Col className={styles.buttons}>
                <button
                  onClick={() => setRoomDropdown(!roomDropdown)}
                  className={`${styles.button} flex h-8 p-1 text-white relative`}
                >
                  <FaBed
                    className="text-white"
                    style={{
                      marginRight: "8px",
                      marginBottom: "2px",
                      marginTop: "2px",
                    }}
                    size={15}
                  />
                  All Room Types
                  <MdOutlineArrowDropDown
                    className="text-white"
                    size={22}
                    style={{ marginLeft: "2px", marginBottom: "2px" }}
                  />
                  {roomDropdown === true && (
                    <div className="bg-white absolute top-8 left-0 w-[100%] text-black p-2 rounded">
                      <div className="rounded p-1 hover:bg-purple-500 hover:text-white">
                        YES
                      </div>
                    </div>
                  )}
                </button>
                <button
                  onClick={() => setPlanDropdown(!planDropdown)}
                  className={`${styles.button} flex h-8 p-1 px-2 text-white relative`}
                >
                  <BsFillTagFill
                    className="text-white"
                    style={{
                      marginRight: "8px",
                      marginBottom: "2px",
                      marginTop: "3px",
                    }}
                  />
                  All Rates Plans
                  <MdOutlineArrowDropDown
                    className="text-white"
                    size={22}
                    style={{ marginLeft: "2px", marginBottom: "4px" }}
                  />
                  {planDropdown === true && (
                    <div
                      className={`${styles.ratePlanDrop} bg-white absolute top-8 left-0 w-[100%] text-black p-2 rounded`}
                    >
                      <div className="rounded p-1 hover:bg-purple-500 hover:text-white">
                        All
                      </div>
                    </div>
                  )}
                </button>
              </Col>
            </Col>
            {/* <Col className={styles.midSection} style={{ border: "none" }}></Col> */}
            {/* <Col className={styles.rightSection}>
              <Row className={styles.data}>
                <Col className={styles.col} style={{ border: "none" }}>
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-evenly",
                      alignItems: "center",
                      width: "100%",
                    }}
                  >
                    <span className={styles.saveButton}>
                      <IoIosSave size={20} />
                    </span>
                    <span className={styles.cancelButton}>
                      <GiCancel size={20} />
                    </span>
                  </div>
                </Col>
              </Row>
            </Col> */}
          </Row>

          <div className={`${styles.item}`}>
            <Row className={`${styles.heading} flex items-center`}>
              <Col className={styles.Icon}>
                <FaBed
                  size={23}
                  className="text-gray-200"
                  style={{ marginTop: "5px" }}
                />
              </Col>
              <Col className={`${styles.leftSection} flex items-center ml-1`}>
                <span className="font-bold text-xl text-gray-200">
                  Deluxe Room
                </span>
              </Col>
              <Col
                className={`${styles.midSection}  text-gray-200 font-semibold`}
              >
                Avail:
              </Col>
              <Col className={styles.rightSection}>
                <Row className={`${styles.data} text-gray-200 font-semibold`}>
                  <Col className={styles.col}>
                    <span className="text-gray-200 font-semibold">YES</span>
                  </Col>
                  <Col className={styles.col}>
                    <span className="text-gray-200 font-semibold">YES</span>
                  </Col>
                  <Col className={styles.col}>
                    <span className="text-gray-200 font-semibold">YES</span>
                  </Col>
                  <Col className={styles.col}>
                    <span className="text-gray-200 font-semibold">YES</span>
                  </Col>
                  <Col className={styles.col}>
                    <span className="text-gray-200 font-semibold">YES</span>
                  </Col>
                  <Col className={styles.col}>
                    <span className="text-gray-200 font-semibold">YES</span>
                  </Col>
                  <Col className={styles.col}>
                    <span className="text-gray-200 font-semibold">YES</span>
                  </Col>
                </Row>
              </Col>
            </Row>
            <Row className={styles.content}>
              <Col className={styles.Icon}></Col>
              <Col
                className={styles.leftSection}
                style={{ flexDirection: "column" }}
              >
                <span
                  className={`${styles.roomsAndPlansPricesSpan} text-base`}
                  style={{ border: "none" }}
                >
                  Room Rates and Plans
                </span>
              </Col>
              <Col className={styles.midSection}>
                <div className={styles.roomsAndPlansPrices}>
                  <span
                    className={`${styles.midSection} font-semibold`}
                    style={{ border: "none" }}
                  >
                    Rates :
                  </span>
                </div>
              </Col>
              <Col className={styles.rightSection}>
                <Row className={styles.data}>
                  <Col className={styles.col}>
                    <div className={styles.roomsAndPlansPrices}>
                      <span
                        className={styles.roomsAndPlansPricesSpan}
                        style={{
                          border: "none",
                          justifyContent: "center",
                        }}
                      >
                        YES
                      </span>
                    </div>
                  </Col>
                  <Col className={styles.col}>
                    <div className={styles.roomsAndPlansPrices}>
                      <span
                        className={styles.roomsAndPlansPricesSpan}
                        style={{
                          border: "none",
                          justifyContent: "center",
                        }}
                      >
                        YES
                      </span>
                    </div>
                  </Col>
                  <Col className={styles.col}>
                    <div className={styles.roomsAndPlansPrices}>
                      <span
                        className={styles.roomsAndPlansPricesSpan}
                        style={{
                          border: "none",
                          justifyContent: "center",
                        }}
                      >
                        YES
                      </span>
                    </div>
                  </Col>
                  <Col className={styles.col}>
                    <div className={styles.roomsAndPlansPrices}>
                      <span
                        className={styles.roomsAndPlansPricesSpan}
                        style={{
                          border: "none",
                          justifyContent: "center",
                        }}
                      >
                        YES
                      </span>
                    </div>
                  </Col>
                  <Col className={styles.col}>
                    <div className={styles.roomsAndPlansPrices}>
                      <span
                        className={styles.roomsAndPlansPricesSpan}
                        style={{
                          border: "none",
                          justifyContent: "center",
                        }}
                      >
                        YES
                      </span>
                    </div>
                  </Col>
                  <Col className={styles.col}>
                    <div className={styles.roomsAndPlansPrices}>
                      <span
                        className={styles.roomsAndPlansPricesSpan}
                        style={{
                          border: "none",
                          justifyContent: "center",
                        }}
                      >
                        YES
                      </span>
                    </div>
                  </Col>
                  <Col className={styles.col}>
                    <div className={styles.roomsAndPlansPrices}>
                      <span
                        className={styles.roomsAndPlansPricesSpan}
                        style={{
                          border: "none",
                          justifyContent: "center",
                        }}
                      >
                        YES
                      </span>
                    </div>
                  </Col>
                </Row>
              </Col>
            </Row>

            {/* <Row className={styles.content}>
              <Col className={styles.Icon}></Col>
              <Col className={styles.leftSection}>
                YES
                <AiFillThunderbolt
                  size={15}
                  style={{
                    marginTop: "5px",
                    color: "#2494d1",
                  }}
                />
              </Col>
              <Col className={styles.midSection}>Plan Rates:</Col>
              <Col className={styles.rightSection}>
                <Row className={styles.data}>
                  <Col className={styles.col}>
                    <span>No Plan</span>
                  </Col>
                  <Col className={styles.col}>
                    <span>No Plan</span>
                  </Col>
                  <Col className={styles.col}>
                    <span>No Plan</span>
                  </Col>
                  <Col className={styles.col}>
                    <span>No Plan</span>
                  </Col>
                  <Col className={styles.col}>
                    <span>No Plan</span>
                  </Col>
                  <Col className={styles.col}>
                    <span>No Plan</span>
                  </Col>
                  <Col className={styles.col}>
                    <span>No Plan</span>
                  </Col>
                </Row>
              </Col>
            </Row> */}
          </div>
        </div>
      </div>
    </>
  );
};

export default ChannelManager;
